version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-lint-server:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: cd frontend
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn run clean

workflows:
  clean:
    jobs:
      - build-and-lint-server