 Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-lint-server:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: cd server 
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn run clean

workflows:
  clean:
    jobs:
      - build-and-lint-server