version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint-server:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Lint
          command: cd ~/project/server && yarn run clean

workflows:
  clean:
    jobs:
      - lint-server