version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-lint-server:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/project/server
          with-cache: false
      - run:
          name: Lint Backend
          command: cd ~/project/server && yarn run clean
  build-and-lint-frontend:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/project/frontend
          with-cache: false
      - run:
          name: Lint Frontend
          command: cd ~/project/frontend && yarn run clean
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/install
      - heroku/deploy-via-git:
          force: true 


workflows:
  clean_deploy:
    jobs:
      - build-and-lint-server
      - build-and-lint-frontend
      - deploy:
          requires:
            - build-and-lint-frontend
            - build-and-lint-server